### PR TITLE
Reimplement Dev mode

### PR DESCRIPTION
**Pull request by alexnguyenn**
## Context
Dev mode is a great addition. However, IMO the current implementation with React Context is needlessly complicated, as `isDevMode` is used only by the Compiler page and its' child components (and I would prefer it staying that way). 

The only benefit of using Context is retaining the value of `isDevMode` while navigating the site. If this is a necessity, I think using `localStorage` or `sessionStorage` will be a better choice. 

## Changelog
* Remove `DevModeContext`.
* ~~Change `isDevMode` to be a prop to be sent down to `CircuitSelect`.~~ `isDevMode` is now a callable function that check the query string for `dev=true`, available in `lib/isDevMode.ts`.
* Stop the behavior where `?dev=true` query string disappears from URL bar upon page load.
* Add `src/lib/` folder for all utilities stuffs.

### CODE REVIEW

**Review by gwwatkin — COMMENTED** [review]
> Stop the behavior where ?dev=true query string disappears from URL bar upon page load.

That is very nice

> Change isDevMode to be a prop to be sent down to CircuitSelect.


I thought the advantage of context was avoiding prop drilling and that app state should be moved into context too. Putting devMode into a prop sounds like more prop drilling, I thought we wanted to avoid it. When I first made appState I used prop drilling becuse it was the quickest thing to do.

As for restricting dev mode to the compiler page, I'm ok with it since I intend to use it there but I don't really mind.

Maybe we move devMode to app state and put appState in context?

@Keelando what do you think?

**Comment by gwwatkin** [comment]
>  Only compiler and its child components used dev mode and app state

At the moment yes. But the whole point of dev mode is that you can add features to experiment, might be a whole new page (like an ls-instruction viewer a debugger page etc.), Now thinking about it more carefully, I think we do want it at the appState/global level.

> context is reserved for stuffs used by the whole site?

I thought context was just a way to avoid prop drilling

**Comment by alexnguyenn** [comment]
> But the whole point of dev mode is that you can add features to experiment, might be a whole new page

The way dev mode can only be triggered now is via the Compiler page. If that is the case then we might have to approach this a bit different. 

> I thought context was just a way to avoid prop drilling, also it fits well with the fact that we don't expect it to change often

If only restricted to compiler then I don't think props drilling is a problem, but if you want to do it globally then yeah it will be better to use Context.

**Comment by gwwatkin** [comment]
> The way dev mode can only be triggered now is via the Compiler page. If that is the case then we might have to approach this a bit different.

I see, yes that is undesirable. We would want it on all pages then.

> wouldn't just a check on the query string is sufficient? Why we need to keep it as a state again?

Makes sense :thinking: we could just have an `isDevMode()` function to check that, got to just make sure it behaves as expected

**Comment by Keelando** [comment]
I guess it depends on what features we bring on with devMode and how much refactoring we end up doing. Using context is likely more robust when it comes to refactoring and bringing in new functionality, since you can import the context directly into any component that needs it.

I do like the query string persisting after page load.

If we want to put the upload circuit page on the home page, and have it render the result on the compiler page, I think we need global app state or context for dev mode to persist across those two pages. I also kind of like allowing devMode to persist across all the pages because I can have a look at other pages while I'm developing and then not have to re-enable it when I come back. 

I am not familiar with localStorage or sessionStorage, but that seems like it worth looking in to.

Context might be overkill for one single dev mode feature, but I think in the longer term it is a viable and robust solution worth considering.

**Comment by alexnguyenn** [comment]
@Keelando please disregard my suggestion about `sessionStorage` and `localStorage`.

As mentioned in above comments, I think Context or any kind of state to store `isDevMode` is unnecessary, since we can just determine if the page is in dev mode via checking the query string with these 2 lines:
https://github.com/latticesurgery-com/web-ui/blob/777b80091908a95dbe71193d6e55fed2e29f59ac/src/pages/Compiler.tsx#L18-L19

**Comment by alexnguyenn** [comment]
Updated the `isDevMode` check to be a function

**Review by gwwatkin — APPROVED** [review]
Good idea making a lib directory. I think this implementation is fine. For now guess we can do with all the Dev features on this page.

@Keelando I still think we need to put AppState in context though.

**Pull request merged**
