### PR TITLE
Add CI/CD

### PR DESCRIPTION
**Pull request by alexnguyenn**
As title. This is how it will work:

When a PR is opened: 
* Github Actions run `npm run lint` and `npm test`.
* If above passed, proceed to `npm run build`.
* Upload the build to Surge for preview.

Once the PR is closed (either rejected or merged)
* Teardown the preview on Surge

If the PR is merged into main - *this part is still WIP*:
* Run the above lint, test and build process again. 
* Deploy to staging (S3). Ask for approval to deploy to production (S3)
* Once it is approved, deploy to production (S3). 

Part of #19

### CODE REVIEW

**Comment by gwwatkin** [comment]
```
Treating warnings as errors because process.env.CI = true.
Most CI servers set it automatically.

Failed to compile.
```
@alexnguyenn  The warnings should't be hard to fix, but I can't get to them right now. I think we'd rather have warnings as errors rather than suppressing them maybe @Keelando could?

**Comment by alexnguyenn** [comment]
@gwwatkin the warning it is returning is [@typescript-eslint/explicit-module-boundary-types](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md). I can:
* Disable the warning - I do think it is kind of redundant to declare type for components. 
* Follow it. We can use `JSX.Element` or `void` as the return type - see [here](https://stackoverflow.com/questions/54814753/typescript-warning-about-missing-return-type-of-function-eslint).

**Comment by gwwatkin** [comment]
If you use the 
```ts
const Component: React.FC<Props> = (props) => (
```
Solution then you should be able to remove Props from the signature of the function making that part easier to read.

> Disable the warning
This warning applies to module boundaries, which is where you land when searching through code with go to definition. In this case the type might be redundant (though the FC solution seems quite concise), but in general having explicit types in places where you land on from a search can save a lot of time down he line

**Comment by gwwatkin** [comment]
That works too :+1:

**Comment by alexnguyenn** [comment]
@gwwatkin It is the solution I saw on Stackoverflow. Feel free to edit it if needed.

**Review by gwwatkin — APPROVED** [review]
Awsome

**Pull request merged**
