### PR TITLE
remove unused code.

### PR DESCRIPTION
**Pull request by Keelando**

### CODE REVIEW

**Comment by Keelando** [comment]
@alexnguyenn  This was the PR associated with the deployment run that was never committed and was sporadically automatically attempting to commit itself. If I re-submit the PR, nothing will change in the code base since the changes are already there, but this will trigger a new workflow run?

**Comment by alexnguyenn** [comment]
You can manually trigger a deployment. If the changes in this PR already in the main branch, then close this and i will manually deploy again

**Comment by Keelando** [comment]
Because I thought allowing production deployments out of order caused problems, I deleted the problem one on git actions. That's what I remember hearing or reading, but I could be mistaken. Since it is deleted now, what do you think we should do?

@alexnguyenn

**Comment by alexnguyenn** [comment]
Closed due to duplication https://github.com/latticesurgery-com/web-ui/pull/176

**Comment by Keelando** [comment]
So this got merged into the repo, but not the deployment. In this particular case, its probably not important at all, but could there be any problems due to something like this happening?

**Comment by alexnguyenn** [comment]
@Keelando sorry for late reply
It should be deployed if a PR after it got deployed

**Comment by Keelando** [comment]
So the weird thing was, it would automatically randomly try deploying weeks later without me doing anything. Do I ended up deleting the deployment it from github actions since it never deployed. Apologies for the confusion and mess. Just trying trying to figure out what's been going on 🙂

**Pull request closed without merging**
