### PR TITLE
Fix nav bar

### PR DESCRIPTION
**Pull request by Keelando**
Added react-bootstrap to dependencies to use pre-packaged react navbar component. Made some layout adjustments to restore navbar to previous state.

### CODE REVIEW

**Review by alexnguyenn — APPROVED** [review]
Checked the preview on my phone and seems like the navbar is working now.

**Review by gwwatkin — APPROVED** [review]

**Comment by alexnguyenn** [comment]
@Keelando I checked the CI/CD log and saw this error.
```
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
```
Seems like you want to upgrade your npm. I already re-run `npm install` on my end to reflect the dependencies update.

**Comment by Keelando** [comment]
Thanks for the catch!

**Comment by Keelando** [comment]
> Checked the preview on my phone and seems like the navbar is working now.

@alexnguyenn, by the way, what do you use for phone testing on the local network? The last time I looked into I, I needed to connect my phone to my computer via USB, but my phone wasn't recognizing USB cables for data transfer. Perhaps an update fixed that by now...

**Comment by alexnguyenn** [comment]
@Keelando We have the pull request preview deployed at https://latticesurgery-com-web-ui-pr38-preview.surge.sh

You should see the bot commented after the checks are run successfully.

**Comment by Keelando** [comment]
Wow, really nice work! 👌

**Pull request merged**
