### PR TITLE
add global gtag for g-analytics

### PR DESCRIPTION
**Pull request by Keelando**
By far the easiest and fastest solution to implement

### CODE REVIEW

**Comment by alexnguyenn** [comment]
@Keelando can you include a reference to the method you used?

**Comment by Keelando** [comment]
If you have a gmail account, you can create an analytics profile. 

From there, they just give you that snippet with your own ID.

You can put more tags on particular components like search bars or input fields but I havent tried those out.

I can dig you up an article though.

**Comment by Keelando** [comment]
[Here is the documentation](https://support.google.com/analytics/answer/9306384)

**Comment by alexnguyenn** [comment]
hmm I do wonder if it is possible to have analytics for only latticesurgery.com, and not dev.latticesurgery.com and any of the previews?

**Comment by Keelando** [comment]
I'm fairly sure we can do that. Might need to include some URL logic

**Review by alexnguyenn — APPROVED** [review]

**Pull request merged**
