### PR TITLE
Add stub of Lattice View to web UI

### PR DESCRIPTION
**Pull request by gwwatkin**
As @Keelando suggested, adding the lattice view directly onto the `UploadCircuit` page (which perhaps might need a new name)
Screenshot_20211102_053451
 
The styles are broken, but the functionality is all there. Passing over to Keelando from here:
- https://github.com/latticesurgery-com/web-ui/issues/8

### CODE REVIEW

**Comment by gwwatkin** [comment]
This is a good example circuit to test:

```qasm
OPENQASM 2.0;
include "qelib1.inc";

qreg q[2];

h q[0];
cx q[0],q[1];
h q[0];
t q[1];
s q[0];
x q[0];
```

**Review by Keelando — APPROVED** [review]
Noticed that `package-lock.json` needs to go in the .gitignore

**Comment by Keelando** [comment]
Will you pull/rebase your commits on reactify-django-website into reactify-django-website-2?

**Comment by gwwatkin** [comment]
@alexnguyenn  Merging

**Comment by gwwatkin** [comment]
@Keelando 
> Will you pull/rebase your commits on reactify-django-website into reactify-django-website-2?

Those commits were squashed and added to main with https://github.com/latticesurgery-com/web-ui/commit/9cd638ca96926519bd3dc11d78245fc53ca3a3d8

**Pull request merged**
