### PR TITLE
Bumping dependencies

### PR DESCRIPTION
**Pull request by alexnguyenn**
CRA recently just released 5.0.0. Here are the release details: https://github.com/facebook/create-react-app/releases/tag/v5.0.0

Also bumping those dependencies to latest versions:
```
Package                            Current    Latest
@emotion/react                      11.7.0    11.7.1
@testing-library/jest-dom           5.16.0    5.16.1  
@testing-library/react              11.2.7    12.1.2
@testing-library/user-event         12.8.3    13.5.0
@types/jest                        26.0.24    27.0.3
@types/jquery                        3.5.9    3.5.10
@types/lodash                     4.14.177  4.14.178
@types/node                       12.20.37    17.0.0
@typescript-eslint/eslint-plugin     5.5.0     5.7.0
@typescript-eslint/parser            5.5.0     5.7.0
prettier                             2.5.0     2.5.1
typescript                           4.5.2     4.5.4
web-vitals                           1.1.2     2.1.2
```

### CODE REVIEW

**Comment by alexnguyenn** [comment]
Also removing ESLint from `package.json` since it is included with CRA already.

**Comment by alexnguyenn** [comment]
Also here is the output when I ran `npm outdated`. Should we bump those dependencies as well?

```
Package                            Current    Wanted    Latest  Location                                       Depended by
@emotion/react                      11.7.0    11.7.1    11.7.1  node_modules/@emotion/react                    web-ui     
@testing-library/jest-dom           5.16.0    5.16.1    5.16.1  node_modules/@testing-library/jest-dom         web-ui     
@testing-library/react              11.2.7    11.2.7    12.1.2  node_modules/@testing-library/react            web-ui     
@testing-library/user-event         12.8.3    12.8.3    13.5.0  node_modules/@testing-library/user-event       web-ui     
@types/jest                        26.0.24   26.0.24    27.0.3  node_modules/@types/jest                       web-ui     
@types/jquery                        3.5.9    3.5.10    3.5.10  node_modules/@types/jquery                     web-ui     
@types/lodash                     4.14.177  4.14.178  4.14.178  node_modules/@types/lodash                     web-ui     
@types/node                       12.20.37  12.20.37    17.0.0  node_modules/@types/node                       web-ui     
@typescript-eslint/eslint-plugin     5.5.0     5.7.0     5.7.0  node_modules/@typescript-eslint/eslint-plugin  web-ui     
@typescript-eslint/parser            5.5.0     5.7.0     5.7.0  node_modules/@typescript-eslint/parser         web-ui     
prettier                             2.5.0     2.5.0     2.5.1  node_modules/prettier                          web-ui     
typescript                           4.5.2     4.5.4     4.5.4  node_modules/typescript                        web-ui     
web-vitals                           1.1.2     1.1.2     2.1.2  node_modules/web-vitals                        web-ui     
```

**Review by gwwatkin — APPROVED** [review]

**Comment by gwwatkin** [comment]
> Also here is the output when I ran `npm outdated`. Should we bump those dependencies as well?

Probably. Maybe better to just set up dependabot

**Comment by alexnguyenn** [comment]
@gwwatkin I will bump them so when we setup Dependabot we don't get bombarded with PRs.

**Comment by gwwatkin** [comment]
@alexnguyenn sounds good

**Pull request merged**
