### PR TITLE
updated favicon

### PR DESCRIPTION
**Pull request by Keelando**

### CODE REVIEW

**Comment by alexnguyenn** [comment]
Seems like the favicon didn't load

**Comment by Keelando** [comment]
OK, I accidentally made it orange instead of blue. I also removed the white padding inside the cell for the favicon because its really tiny and I think it shows up better in the browser tab

**Comment by Keelando** [comment]
> Seems like the favicon didn't load

Yeah I noticed it doesn't show up in surge either. But it shows up locally.

Possibly changing the extension to .ico changed something but I updated the filename where favicon is called

**Comment by alexnguyenn** [comment]
Seems like the file is not available on Github either? Check https://github.com/latticesurgery-com/web-ui/blob/26593742d36fd885c2cb8d89f80b42064165eb5c/public/favicon.jpg

I used `favicon.ico` in the my other React repo and it seems to be showing up fine.

**Pull request closed without merging**
